### ISSUE TITLE
Put an asciinema video of its running right on your readme page, so people can get the visual feedback

### ISSUE THREAD

**Issue by unixbhaskar** [k3nny-wx/emwa#3]
Modern-day new adoption strategy to look at the eyes. Moreover, before compiling and working with it, people might want to see, it as it is a userspace tool.

Adoption is key, the best way to hook this gen people to use it by giving them eye candy stuff in the first place.

**Comment by snow-dll** [comment]
Noted, will be added.

**Comment by snow-dll** [comment]
README.md has been updated to include a preview / image link.
